version: '2'
services:
  backend:
    build:
      context: ../back/demo
#      dockerfile: src/main/docker/Dockerfile
      dockerfile: src/main/docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}?useSSL=false
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
    depends_on:
      - postgres


  postgres:
    image: "postgres:11-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_HOST_AUTH_METHOD: trust
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
